- name: Beegfs Management storage
  hosts: mgmt
  become: yes
  tasks:
#    - name: Show device information
#      parted: 
#        device: "{{ item.device }}"
#        unit: GiB
#        state: info
#      with_items: "{{ hostvars[inventory_hostname].mt_devices }}"
#      register: disk_parted
#
#    - name: Print device information
#      debug:
#        msg: System {{ inventory_hostname }} device {{ item.disk.dev }} size {{ item.disk.size }} partitions {{ item.partitions|length }}
#      with_items: "{{ disk_parted['results'] }}"
#

    - name: Create the directory for the management data
      file:
        path: "/{{ hostvars[inventory_hostname].mg_path }}/{{ item.dir }}"
        state: directory
        mode: '0755'
      with_items: "{{ hostvars[inventory_hostname].mg_devices }}"
      when: item.type == "SYNC"

    - name: Create the directory for the sync target
      file:
        path: "/{{ hostvars[inventory_hostname].mg_path }}/{{ item.syncdir }}"
        state: directory
        mode: '0755'
      with_items: "{{ hostvars[inventory_hostname].mg_devices }}"
      when: item.type == "SYNC"

    - name: Create the directory for the beegfs secret
      file:
        path: /etc/beegfs
        state: directory
        mode: '0750'
      with_items: "{{ hostvars[inventory_hostname].mg_devices }}"
      when: item.type == "SYNC"

    - name: Copy TLS cert
      copy:
        src: files/cert.pem
        dest: /etc/beegfs/cert.pem
        owner: root
        group: root
        mode: '0400'

    - name: Copy TLS key
      copy:
        src: files/key.pem
        dest: /etc/beegfs/key.pem
        owner: root
        group: root
        mode: '0400'

    - name: Copy security configuration
      copy:
        src: files/conn.auth
        dest: /etc/beegfs/conn.auth
        owner: root
        group: root
        mode: '0400'

    - name: Copy mkcompose script
      copy:
        src: ./scripts/mkcompose
        dest: /tmp/mkcompose
        mode: 'u=rwx,g=rwx'
        force: yes
      with_items: "{{ hostvars[inventory_hostname].mg_devices }}"
      when: item.type == "SYNC"

    - name: Run the mkcompose script to create the docker-compose.yaml file
      command:
        argv:
        - "/tmp/mkcompose"
        - "{{ beegfs_version }}"
        - "0"
        - "mgmt"
      with_items: "{{ hostvars[inventory_hostname].mg_devices }} "
      when: item.type == "SYNC"

    - name: Remove existing beegfs firewall rules for TCP
      ufw:
        rule: allow
        port: 8003:8010
        proto: tcp
        delete: true

    - name: Remove existing beegfs firewall rules for UDP
      ufw:
        rule: allow
        port: 8003:8010
        proto: udp
        delete: true

    - name: Add beegfs firewall rules for TCP
      ufw:
        rule: allow
        port: 8003:8010
        proto: tcp
        src: '{{ item }}'
      loop:
        - 10.88.0.0/16
        - 10.19.0.0/16

    - name: Add beegfs firewall rules for UDP
      ufw:
        rule: allow
        port: 8003:8010
        proto: udp
        src: '{{ item }}'
      loop:
        - 10.88.0.0/16
        - 10.19.0.0/16

    - name: Enable ufw
      ufw:
        state: enabled
