- name: Beegfs Storage Volumes
  hosts: storage
  become: yes
  tasks:
#    - name: Show device information
#      parted: 
#        device: "{{ item.device }}"
#        unit: GiB
#        state: info
#      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
#      register: disk_parted
#
#    - name: Print device information
#      debug:
#        msg: System {{ inventory_hostname }} device {{ item.disk.dev }} size {{ item.disk.size }} partitions {{ item.partitions|length }}
#      with_items: "{{ disk_parted['results'] }}"
#
    - name: Install zfs
      apt:
        name:
          - zfsutils-linux 
          - zfs-dkms
          - libzfslinux-dev
        state: present

    - name: Collect disk info
      parted:
        device: "{{ item.device }}"
        unit: GiB
        state: info
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "RAID"

    - name: Create a new primary partition
      community.general.parted:
        device: "{{ item.device }}"
        number: 1
        state: present
        fs_type: xfs
        part_end: 100%
        label: gpt
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "RAID"

    - name: Create an XFS filesystem on the new partition
      community.general.filesystem:
        fstype: xfs
        dev: "{{ item.device }}1"
        state: present
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "RAID"

    - name: Label the XFS filesystem
      command: xfs_admin -L "{{ hostvars[inventory_hostname].st_prefix }}{{ hostvars[inventory_hostname].st_nodeid }}{{ item.target }}" "{{ item.device }}1"
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "RAID"

    - name: Create the mount point for the filesystem
      file:
        path: "{{ hostvars[inventory_hostname].st_path }}/{{ hostvars[inventory_hostname].st_prefix }}{{ hostvars[inventory_hostname].st_nodeid }}{{ item.target }}"
        state: directory
        mode: '0755'
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "RAID"

    - name: Mount the storage target filesystem
      ansible.posix.mount:
        path: "{{ hostvars[inventory_hostname].st_path }}/{{ hostvars[inventory_hostname].st_prefix }}{{ hostvars[inventory_hostname].st_nodeid }}{{ item.target }}"
        src: LABEL={{ hostvars[inventory_hostname].st_prefix }}{{ hostvars[inventory_hostname].st_nodeid }}{{ item.target }}
        fstype: xfs
        state: mounted
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "RAID"

    - name: Copy scratch disk script
      copy:
        src: ./scripts/mkzfs
        dest: /tmp/mkzfs
        mode: 'u=rwx,g=rwx'
        force: yes
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "ZFS"

    - name: Prepare the script to create zfs pools
      command:
        argv:
        - "/tmp/mkzfs"
        - "{{ item.wipedisk }}"
        - "{{ item.device }}"
        - "{{ item.partition }}"
        - "{{ hostvars[inventory_hostname].st_pools}}"
        - "{{ hostvars[inventory_hostname].st_disks}}"
        - "{{ hostvars[inventory_hostname].st_path }}"
        - "{{ hostvars[inventory_hostname].st_pool }}"
        - "{{ hostvars[inventory_hostname].st_type}}"
      with_items: "{{ hostvars[inventory_hostname].st_devices }} "
      when: item.raid == "ZFS"

    - name: Run the mkzpool script
      command: "bash /tmp/mkzpool"
      with_items: "{{ hostvars[inventory_hostname].st_devices }} "
      when: item.raid == "ZFS"

    - name: Copy the zpool validation script
      copy:
        src: ./scripts/ckzfs
        dest: /tmp/ckzfs
        mode: 'u=rwx,g=rwx'
        force: yes
      with_items: "{{ hostvars[inventory_hostname].st_devices }}"
      when: item.raid == "ZFS"

    - name: Verify the zpools were created
      command:
        argv:
        - "/tmp/ckzfs"
        - "{{ hostvars[inventory_hostname].st_pools}}"
        - "{{ hostvars[inventory_hostname].st_pool }}"
      with_items: "{{ hostvars[inventory_hostname].st_devices }} "
      when: item.raid == "ZFS"

    - name: Create the directory for the beegfs secret
      file:
        path: /etc/beegfs
        state: directory
        mode: '0750'

    - name: Copy TLS cert
      copy:
        src: files/cert.pem
        dest: /etc/beegfs/cert.pem
        owner: root
        group: root
        mode: '0400'

    - name: Copy TLS key
      copy:
        src: files/key.pem
        dest: /etc/beegfs/key.pem
        owner: root
        group: root
        mode: '0400'

    - name: Copy security configuration
      copy:
        src: files/conn.auth
        dest: /etc/beegfs/conn.auth
        owner: root
        group: root
        mode: '0400'

    - name: Copy mkcompose script
      copy:
        src: ./scripts/mkcompose
        dest: /tmp/mkcompose
        mode: 'u=rwx,g=rwx'
        force: yes

    - name: Run the mkcompose script to create the docker-compose.yaml file
      command:
        argv:
        - "/tmp/mkcompose"
        - "{{ beegfs_version }}"
        - "{{ hostvars[inventory_hostname].st_nodeid }}"
        - "storage"

    - name: Remove existing beegfs firewall rules for TCP
      ufw:
        rule: allow
        port: 8003:8010
        proto: tcp
        delete: true

    - name: Remove existing beegfs firewall rules for UDP
      ufw:
        rule: allow
        port: 8003:8010
        proto: udp
        delete: true

    - name: Add beegfs firewall rules for TCP
      ufw:
        rule: allow
        port: 8003:8010
        proto: tcp
        src: '{{ item }}'
      loop:
        - 10.88.0.0/16
        - 10.19.0.0/16

    - name: Add beegfs firewall rules for UDP
      ufw:
        rule: allow
        port: 8003:8010
        proto: udp
        src: '{{ item }}'
      loop:
        - 10.88.0.0/16
        - 10.19.0.0/16


    - name: Enable ufw
      ufw:
        state: enabled
